# Generated by Django 3.2.12 on 2023-10-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='crud_app_userprofile',
        ),
    ]
